name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Java এনভায়রনমেন্ট সেটআপ
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    # গ্র্যাডল ফাইল রান করার পারমিশন দেওয়া
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    # ডিবাগ APK বিল্ড করা
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # তৈরি হওয়া APK ফাইলটি গিটহাবে আপলোড করা
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-android-app-apk
        path: app/build/outputs/apk/debug/*.apk
        
